snapshot of project "ncurses", label v5_4_20040711

diff --git a/misc/run_tic.in b/misc/run_tic.in
--- a/misc/run_tic.in
+++ b/misc/run_tic.in
@@ -29,7 +29,7 @@
 #
 # Author: Thomas E. Dickey 1996,2000
 #
-# $Id: run_tic.in,v 1.16 2004/07/04 00:35:27 tom Exp $
+# $Id: run_tic.in,v 1.17 2004/07/11 15:11:14 tom Exp $
 # This script is used to install terminfo.src using tic.  We use a script
 # because the path checking is too awkward to do in a makefile.
 #
@@ -54,6 +54,7 @@ echo '** Building terminfo database, please wait...'
 : ${LN_S="@LN_S@"}
 : ${THAT_CC=cc}
 : ${THIS_CC=cc}
+: ${ext_funcs=@NCURSES_EXT_FUNCS@}
 
 test -z "${DESTDIR}" && DESTDIR=
 
@@ -93,22 +94,12 @@ TICDIR=`echo $TERMINFO | sed -e 's%/share/%/lib/%'`
 # the directory is actually a symbolic link.
 ( cd $TERMINFO && rm -fr ? 2>/dev/null )
 
-# If we're not installing into /usr/share/, we'll have to adjust the location
-# of the tabset files in terminfo.src (which are in a parallel directory).
-TABSET=`echo $ticdir | sed -e 's%/terminfo$%/tabset%'`
-if test "x$TABSET" != "x/usr/share/tabset" ; then
-	echo '** adjusting tabset paths'
-	TMP=${TMPDIR-/tmp}/$$
-	sed -e s%/usr/share/tabset%$TABSET%g $source >$TMP
-	trap "rm -f $TMP" 0 1 2 5 15
-	source=$TMP
-fi
-
+if test "$ext_funcs" = 1 ; then
 cat <<EOF
 Running tic to install $TERMINFO ...
 
 	You may see messages regarding extended capabilities, e.g., AX.
-	These are extended terminal capabilities which are be compiled
+	These are extended terminal capabilities which are compiled
 	using
 		tic -x
 	If you have ncurses 4.2 applications, you should read the INSTALL
@@ -121,6 +112,26 @@ then
 else
 	echo '? tic could not build '$TERMINFO
 	exit 1
+fi
+else
+cat <<EOF
+Running tic to install $TERMINFO ...
+
+	You may see messages regarding unknown capabilities, e.g., AX.
+	These are extended terminal capabilities which may be compiled
+	using
+		tic -x
+	If you have ncurses 4.2 applications, you should read the INSTALL
+	document, and install the terminfo without the -x option.
+
+EOF
+if ( $SHLIB tic$suffix -s -o $TERMINFO $source )
+then
+	echo '** built new '$TERMINFO
+else
+	echo '? tic could not build '$TERMINFO
+	exit 1
+fi
 fi
 
 # Make a symbolic link to provide compatibility with applications that expect
