snapshot of project "ncurses", label v6_6_20260627

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.833 .
+# From configure.in Revision: 1.836 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20260412.
 #
@@ -30119,6 +30119,29 @@ echo "${ECHO_T}$cf_cv_ld_searchpath" >&6
 
 LD_SEARCHPATH=`echo "$cf_cv_ld_searchpath"|sed -e 's/ /|/g'`
 
+PC_FILES=
+for cf_pc_root in \
+	"${LIB_NAME}${USE_ARG_SUFFIX}" \
+	"${TINFO_ARG_SUFFIX}" \
+	"${TICS_NAME}${USE_ARG_SUFFIX}" \
+	"${PANEL_NAME}${USE_ARG_SUFFIX}" \
+	"${MENU_NAME}${USE_ARG_SUFFIX}" \
+	"${FORM_NAME}${USE_ARG_SUFFIX}" \
+	"${CXX_NAME}${USE_ARG_SUFFIX}"
+do
+	cf_pc_file="${cf_pc_root}${PC_MODULE_SUFFIX}".pc
+	cf_found=
+	for cf_pc_used in $PC_FILES
+	do
+		if test "$cf_pc_used" = "$cf_pc_file"
+		then
+			cf_found=$cf_pc_used
+			break
+		fi
+	done
+	test -z "$cf_found" && PC_FILES="$PC_FILES $cf_pc_file"
+done
+
 ac_config_files="$ac_config_files include/MKterm.h.awk include/curses.head:include/curses.h.in include/ncurses_dll.h include/nc_win32.h include/termcap.h include/unctrl.h man/MKterminfo.tmp:man/MKterminfo.sh man/man_db.renames $SUB_MAKEFILES Makefile"
 
 ac_config_commands="$ac_config_commands default"
@@ -30204,7 +30227,7 @@ DEFS=-DHAVE_CONFIG_H
 : "${CONFIG_STATUS=./config.status}"
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:30207: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:30230: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >"$CONFIG_STATUS" <<_ACEOF
 #! $SHELL
@@ -30385,7 +30408,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:30388: error: ambiguous option: $1
+    { { echo "$as_me:30411: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -30404,7 +30427,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:30407: error: unrecognized option: $1
+  -*) { { echo "$as_me:30430: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -30538,7 +30561,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "include/ncurses_cfg.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ncurses_cfg.h:include/ncurses_cfg.hin" ;;
-  *) { { echo "$as_me:30541: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:30564: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -30940,6 +30963,7 @@ s,@CHECK_BUILD@,$CHECK_BUILD,;t t
 s,@PRIVATE_LIBS@,$PRIVATE_LIBS,;t t
 s,@NO_SHARED@,$NO_SHARED,;t t
 s,@LD_SEARCHPATH@,$LD_SEARCHPATH,;t t
+s,@PC_FILES@,$PC_FILES,;t t
 CEOF
 
 EOF
@@ -31072,7 +31096,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:31075: creating $ac_file" >&5
+    { echo "$as_me:31099: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -31090,7 +31114,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:31093: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:31117: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -31103,7 +31127,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:31106: error: cannot find input file: $f" >&5
+           { { echo "$as_me:31130: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -31119,7 +31143,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:31122: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:31146: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -31128,7 +31152,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:31131: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:31155: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -31173,7 +31197,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:31176: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:31200: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -31184,7 +31208,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:31187: WARNING: Some variables may not be substituted:
+      { echo "$as_me:31211: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -31233,7 +31257,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:31236: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:31260: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -31244,7 +31268,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:31247: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:31271: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -31257,7 +31281,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:31260: error: cannot find input file: $f" >&5
+           { { echo "$as_me:31284: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -31315,7 +31339,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
   rm -f "$tmp"/in
   if test x"$ac_file" != x-; then
     if cmp -s "$ac_file" "$tmp/config.h" 2>/dev/null; then
-      { echo "$as_me:31318: $ac_file is unchanged" >&5
+      { echo "$as_me:31342: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -31413,6 +31437,7 @@ do
 
 		SHARED_LIB=
 		Libs_To_Make=
+		Libs_To_Install=
 		cf_awk_program=
 		if test -n "${cf_cv_abi_default}" && test "x${cf_cv_abi_default}" != "x5"
 		then
@@ -31615,12 +31640,18 @@ eval cf_libname="\$${cf_map_lib_basename}_NAME"
 			fi
 			cf_add_lib="../lib/${cf_prefix}${cf_libname}${cf_suffix}"
 			Libs_To_Make="$Libs_To_Make $cf_add_lib"
+			if test "$cf_item" = shared && test "$cf_dir" != c++
+			then
+				cf_add_inst='$(LIBDIR)'"/${cf_prefix}${cf_libname}${cf_suffix}"
+				Libs_To_Install="$Libs_To_Install $cf_add_inst"
+			fi
 		done
 
 		if test "$cf_dir" = ncurses ; then
 			cf_subsets="$LIB_SUBSETS"
 			cf_r_parts="$cf_subsets"
 			cf_liblist="$Libs_To_Make"
+			cf_instlist="$Libs_To_Install"
 
 			while test -n "$cf_r_parts"
 			do
@@ -31631,9 +31662,11 @@ eval cf_libname="\$${cf_map_lib_basename}_NAME"
 					case "$cf_l_parts" in
 					(*termlib*)
 						cf_add_lib=`echo "$cf_liblist" |sed -e s%${LIB_NAME}${ABI_SUFFIX}%${TINFO_LIB_SUFFIX}%g`
+						cf_add_inst=`echo "$cf_instlist" |sed -e s%${LIB_NAME}${ABI_SUFFIX}%${TINFO_LIB_SUFFIX}%g`
 						;;
 					(*ticlib*)
 						cf_add_lib=`echo "$cf_liblist" |sed -e s%${LIB_NAME}${ABI_SUFFIX}%${TICS_LIB_SUFFIX}%g`
+						cf_add_inst=`echo "$cf_instlist" |sed -e s%${LIB_NAME}${ABI_SUFFIX}%${TICS_LIB_SUFFIX}%g`
 						;;
 					(*)
 						break
@@ -31641,6 +31674,9 @@ eval cf_libname="\$${cf_map_lib_basename}_NAME"
 					esac
 					if test -n "$cf_add_lib"; then
 						Libs_To_Make="$cf_add_lib $Libs_To_Make"
+					fi
+					if test -n "$cf_add_inst"; then
+						Libs_To_Install="$cf_add_inst $Libs_To_Install"
 					fi
 				else
 					break
@@ -31678,6 +31714,7 @@ eval cf_libname="\$${cf_map_lib_basename}_NAME"
 		fi
 
 		sed -e "s%@Libs_To_Make@%$Libs_To_Make%" \
+		    -e "s%@Libs_To_Install@%$Libs_To_Install%" \
 		    -e "s%@SHARED_LIB@%$SHARED_LIB%" \
 			"$cf_dir/Makefile" >$cf_dir/Makefile.out
 		mv "$cf_dir/Makefile.out" "$cf_dir/Makefile"
@@ -31702,7 +31739,7 @@ cf_ITEM=`echo "$cf_item" | sed y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQ
 				(cygdll|msysdll|mingw|msvcdll)
 					test "x$with_shared_cxx" = xno && test -n "$verbose" && echo "	overriding CXX_MODEL to SHARED" 1>&6
 
-echo "${as_me:-configure}:31705: testing overriding CXX_MODEL to SHARED ..." 1>&5
+echo "${as_me:-configure}:31742: testing overriding CXX_MODEL to SHARED ..." 1>&5
 
 					with_shared_cxx=yes
 					;;
