snapshot of project "ncurses", label v6_5_20250614

diff --git a/Ada95/configure b/Ada95/configure
--- a/Ada95/configure
+++ b/Ada95/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.in Revision: 1.94 .
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20240618.
+# Generated by Autoconf 2.52.20250126.
 #
 # Copyright 2003-2022,2023	Thomas E. Dickey
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -829,7 +829,7 @@ This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
 It was created by $as_me, which was
-generated by GNU Autoconf 2.52.20240618.  Invocation command line was
+generated by GNU Autoconf 2.52.20250126.  Invocation command line was
 
   $ $0 $@
 
@@ -18724,13 +18724,13 @@ main (void)
 #ifndef __cplusplus
   /* Ultrix mips cc rejects this.  */
   typedef int charset[2];
-  const charset x; (void)x;
+  const charset x;
   /* SunOS 4.1.1 cc rejects this.  */
   char const *const *ccp;
   char **p;
   /* NEC SVR4.0.2 mips cc rejects this.  */
   struct point {int x, y;};
-  static struct point const zero = {0,0}; (void)zero;
+  static struct point const zero = {0,0};
   /* AIX XL C 1.02.0.0 rejects this.
      It does not let you subtract one const X* pointer from another in
      an arm of an if-expression whose if-part is not a constant
@@ -18746,7 +18746,7 @@ main (void)
     char const *s = 0 ? (char *) 0 : (char const *) 0;
 
     *t++ = 0;
-	(void)s;
+	(void)s; (void)x; (void)zero;
   }
   { /* Someone thinks the Sun supposedly-ANSI compiler will reject this.  */
     int x[] = {25, 17};
@@ -19938,7 +19938,7 @@ EOF
 cat >>"$CONFIG_STATUS" <<EOF
 ac_cs_version="\\
 config.status
-configured by $0, generated by GNU Autoconf 2.52.20240618,
+configured by $0, generated by GNU Autoconf 2.52.20250126,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 2003-2022,2023	Thomas E. Dickey
@@ -20021,7 +20021,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me 2.52.20240618, executed with
+This file was extended by $as_me 2.52.20250126, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -20242,9 +20242,6 @@ s,@NCURSES_MINOR@,$NCURSES_MINOR,;t t
 s,@NCURSES_PATCH@,$NCURSES_PATCH,;t t
 s,@cf_cv_rel_version@,$cf_cv_rel_version,;t t
 s,@cf_cv_abi_version@,$cf_cv_abi_version,;t t
-s,@cf_cv_builtin_bool@,$cf_cv_builtin_bool,;t t
-s,@cf_cv_header_stdbool_h@,$cf_cv_header_stdbool_h,;t t
-s,@cf_cv_type_of_bool@,$cf_cv_type_of_bool,;t t
 s,@cf_cv_enable_sigwinch@,$cf_cv_enable_sigwinch,;t t
 s,@LIB_PREFIX@,$LIB_PREFIX,;t t
 s,@LIB_SUFFIX@,$LIB_SUFFIX,;t t
@@ -20445,7 +20442,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20448: creating $ac_file" >&5
+    { echo "$as_me:20445: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20463,7 +20460,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20466: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20463: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -20476,7 +20473,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:20479: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20476: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20492,7 +20489,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:20495: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:20492: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -20501,7 +20498,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:20504: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:20501: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -20546,7 +20543,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:20549: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:20546: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -20557,7 +20554,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:20560: WARNING: Some variables may not be substituted:
+      { echo "$as_me:20557: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -20606,7 +20603,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20609: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20606: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20617,7 +20614,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20620: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20617: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20630,7 +20627,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:20633: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20630: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20688,7 +20685,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
   rm -f "$tmp"/in
   if test x"$ac_file" != x-; then
     if cmp -s "$ac_file" "$tmp/config.h" 2>/dev/null; then
-      { echo "$as_me:20691: $ac_file is unchanged" >&5
+      { echo "$as_me:20688: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
